#version: "3.8"
name: expense
networks:
  default:
    name: expense
volumes:
  -data-volume:
services:
  #db container and volume for store the data related to db for backup
  mysql:
    image: mysql:v1.0.0
    contianer_name: mysql # --name mysql
    valumes:
      - data-volume:/var/lib/mysql-data
  #backend container and volume
  backend:
    image: backend:v1.0.0
    container_name: backend # --name backend
    valumes:
      - data-volume:/var/lib/backend-data
    depends_on: 
    - mysql
    command: sh -c "sleep 20 && node /opt/server/index.js"
  #frontend container volume 
  forntend:
    image: frontend:v1.0.0
    container_name: frontend # --name frontend
    valumes:
      - data-volume:/var/lib/frontend-data
    depends_on: 
    - backend
    ports: 
    - "80:80"
  
