version: "3.9"
name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
    external: true  
services:
  #db container and volume for store the data related to db for backup
  mysql:
    image: mysql:v1.0
    container_name: mysql # --name mysql
    volumes:
      - source: mysql # -v volume-name: /path/in/container
        target: /var/lib/mysql
        type: volume
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MSQL_USER=expense
  #backend container and volume
  backend:
    image: backend:v1.0
    container_name: backend # --name backend
    command: sh -c "sleep 20 && node /opt/server/index.js" #this will wait for mysql creation because while creating mysql backend already been created so backend can't wait for mysql so we need to wait for mysql creations then backend will creates
    depends_on: 
    - mysql
  #frontend container volume 
  frontend:
    image: frontend:v1.0
    container_name: frontend # --name frontend
    depends_on: 
    - backend
    ports: 
    - "80:80"
  
