#version: "3.8"
name: expense
networks:
  default:
    name: expense
volumes:
  data-volume:
    external: true
services:
  #db container and volume for store the data related to db for backup
  mysql:
    image: mysql:v1.0.0
    contianer_name: mysql # --name mysql
    volumes:
      - data-volume:/db
  #backend container and volume
  backend:
    image: backend:v1.0.0
    container_name: backend # --name backend
    valumes:
      - - data-volume:/backend
    depends_on: 
    - mysql
    command: sh -c "sleep 20 && node /opt/server/index.js" #this will wait for mysql creation because while creating mysql backend already been created so backend can't wait for mysql so we need to wait for mysql creations then backend will creates
  #frontend container volume 
  forntend:
    image: frontend:v1.0.0
    container_name: frontend # --name frontend
    volumes:
      - - data-volume:/frontend
    depends_on: 
    - backend
    ports: 
    - "80:80"
  
